#seed file updated Feb 1, 2017 from 2011 document

members = Member.create([
	{ name: 'Yuet Meng Kwan', number: '1', birthdate: 1858, deathdate: 1913 },
	{ name: 'Hin-Cheong Lau', number: '1S', birthdate: 1849 },

	{ name: 'Keng Wan Kwan', number: '2', birthdate: 1860, deathdate: 1923 },
	{ name: 'Yim-Kheng Lam', number: '2S', birthdate: 1865, deathdate: 1924 },
	{ name: 'Yaw-Yuan Kwan', number: '2-1', birthdate: 1887 },
	{ name: 'Chee-Phang Chooi ', number: '2-1S' },
	{ name: 'Shiu-Kei Kwan', number: '2-2', birthdate: 1890, deathdate: 1928 },
	{ name: 'Sau-Sang Loke', number: '2-2S', birthdate: 1890 },
	{ name: 'David Chun-Shi Kwan', number: '2-2-1', birthdate: 1918, deathdate: 1989 },
	{ name: 'Ruth Ho', number: '2-2-1S', birthdate: 1918, deathdate: 2016 },
	{ name: 'Andrew Pun Li Kwan', number: '2-2-1-1', birthdate: 1946 },
	{ name: 'Suzie Sui Ling Wong', number: '2-2-1-1S', birthdate: 1945 },
	{ name: 'Christie Tung Ying Kwan', number: '2-2-1-1-1', birthdate: 1977 },
	{ name: 'Clifford Tung Gen Kwan', number: '2-2-1-1-2', birthdate: 1980 },
	{ name: 'Dina Tung En Kwan', number: '2-2-1-1-3', birthdate: 1981 },
	{ name: 'Alec Pun Hung Kwan ', number: '2-2-1-2', birthdate: 1949 },
	{ name: 'May Man', number: '2-2-1-2S', birthdate: 1950 },
	{ name: 'Carissa Tungshi Kwan', number: '2-2-1-2-1', birthdate: 1984 },
	{ name: 'Irene Kwan', number: '2-2-1-3', birthdate: 1951 },
	{ name: 'Eddie Chu', number: '2-2-1-3S', birthdate: 1949 },
	{ name: 'Darin Guang-Huei Chu', number: '2-2-1-3-1', birthdate: 1979 },
	{ name: 'Stephanie Hsiao-Chien Chu', number: '2-2-1-3-2', birthdate: 1982 },
	{ name: 'Sylvia Kwan', number: '2-2-1-4', birthdate: 1954 },
	{ name: 'Denis Henmi ', number: '2-2-1-4S', birthdate: 1950 },	
	{ name: 'Drew Kwan Henmi', number: '2-2-1-4-1', birthdate: 1988 },
	{ name: 'Derek Kwan Henmi ', number: '2-2-1-4-2', birthdate: 1991 },
	{ name: 'Nina Kwan', number: '2-2-1-5', birthdate: 1956 },
	{ name: 'Roy Howell', number: '2-2-1-5S', birthdate: 1954 },
	{ name: 'David Kwan Howell', number: '2-2-1-5-1', birthdate: 1994 },
	{ name: 'Frances Kwan Howell', number: '2-2-1-5-2', birthdate: 1996 },
	{ name: 'William Kwan Howell ', number: '2-2-1-5-3', birthdate: 1996 },
	{ name: 'Phoebe Punshan Kwan', number: '2-2-1-6', birthdate: 1958 },
	{ name: 'Ralph Leighton', number: '2-2-1-6S', birthdate: 1949 },
	{ name: 'Ian David Leighton', number: '2-2-1-6-1', birthdate: 1989 },
	{ name: 'Nicole Kwan Leighton', number: '2-2-1-6-2', birthdate: 1991 },
	{ name: 'Martha  Yao-Yuen Kwan', number: '2-3', birthdate: 1892, deathdate: 1970 },
	{ name: 'King-Tak Yeung', number: '2-3S', birthdate: 1891, deathdate: 1972 },
	{ name: 'Hattie Sek-Yu Young', number: '2-3-1', birthdate: 1923, deathdate: 2007 },
	{ name: 'Harry Chang', number: '2-3-1S', birthdate: 1925, deathdate: 2010 },
	{ name: 'William Chang', number: '2-3-1-1', birthdate: 1960 },
	{ name: 'Marisa Lo Chang', number: '2-3-1-1S', birthdate: 1963 },
	{ name: 'Gabriela Chang', number: '2-3-1-1-1', birthdate: 1991 },
	{ name: 'Magdalene', number: '2-3-1-1-2', birthdate: 1995 },
	{ name: 'Druscilla Shueu-Yu Yeung', number: '2-3-2', birthdate: 1924 },
	{ name: 'Ming-Tak Cheuk', number: '2-3-2S', birthdate: 1921, deathdate: 2005 },
	{ name: 'Esther Cheuk', number: '2-3-2-1', birthdate: 1952 },
	{ name: 'Ko Wing-Leung', number: '2-3-2-1S', note: 'divorced; 2 children and grandchildren' },
	{ name: 'Miriam Jieling Cheuk', number: '2-3-2-2', birthdate: 1953 },
	{ name: 'Theodore Cheuk', number: '2-3-2-3', birthdate: 1955 },
	{ name: 'Grace', number: '2-3-2-3S', note: 'have a girl and a boy, and grandchildren' },
	{ name: 'Simon Cheuk', number: '2-3-2-4', birthdate: 1957 },
	{ name: 'Doreen Wai-Yee Yeung', number: '2-3-3', birthdate: 1928, deathdate: 1986 },
	{ name: 'Wei-Peng Shiao', number: '2-3-3S', birthdate: 1929, deathdate: 2009 },
	{ name: 'Wen-Can Shiao', number: '2-3-3-1' },
	{ name: 'Wen-Qi Shiao', number: '2-3-3-2' },
	{ name: 'Wen-Chao Shiao', number: '2-3-3-3' },
	{ name: 'Wen-Lan Shiao', number: '2-3-3-4' },
	{ name: 'Wen-Lou Shiao', number: '2-3-3-5' },
	{ name: 'Phoebe Sum-Yu Yeung', number: '2-3-4', birthdate: 1930 },
	{ name: 'Timothy Chun-Chen Ling', number: '2-3-4S', birthdate: 1926, deathdate: 2008 },
	{ name: 'Marina Hsin Ling', number: '2-3-4-1', birthdate: 1959 },
	{ name: 'Ya-hong Xie', number: '2-3-4-1S', birthdate: 1956 },
	{ name: 'Kira Yiwen Xie', number: '2-3-4-1-1', birthdate: 1991 },
	{ name: 'Justin Yitao Xie', number: '2-3-4-1-2', birthdate: 1992 },
	{ name: 'Stephen En Ling', number: '2-3-4-2', birthdate: 1960 },
	{ name: 'April Heung', number: '2-3-4-2S', birthdate: 1963 },
	{ name: 'Jeremy Ling', number: '2-3-4-2-1', birthdate: 1996 },
	{ name: 'Elliot Ling', number: '2-3-4-2-2', birthdate: 1998 },
	{ name: 'Anna Yuen-Yu Young', number: '2-3-5', birthdate: 1935 },
	{ name: 'Daniel Chang', number: '2-3-5S', birthdate: 1935 },
	{ name: 'Isaac Chang', number: '2-3-5-1' },
	{ name: 'Elizabeth Chang', number: '2-3-5-2' },
	{ name: 'Jerry Tindol', number: '2-3-5-2S' },
	{ name: 'Joshua Hiser', number: '2-3-5-2-1' },
	{ name: 'Jennifer Hiser', number: '2-3-5-2-2' },
	{ name: 'Hannah Chang', number: '2-3-5-3' },
	{ name: 'Scott Burford', number: '2-3-5-3S' },
	{ name: 'Christopher Burford', number: '2-3-5-3-1' },
	{ name: 'Michelle Burford', number: '2-3-5-3-2' },
	{ name: 'Yaw-Yin Kwan', number: '2-4', birthdate: 1894 },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	{ name: '', number: '', birthdate: , deathdate:  },
	
	
	{ name: 'Keng Doh Kwan', number: '3', birthdate: 1862, deathdate: 1889 },
	{ name: 'Keng-Woon', number: '4', birthdate: 1964, deathdate: 1864 },

	{ name: 'Yuet-Peng Kwan', number: '5', birthdate: 1865, deathdate: 1899 },
	{ name: 'Ping-Chung Wen', number: '5S', birthdate: 1862, deathdate: 1938 },
	{ name: 'Hannah Wen', number: '5-1', birthdate: 1882, note: 'adopted' },
	{ name: 'Samuel Y Lee', number: '5-1S', birthdate: 1875, deathdate: 1908 },

	{ name: 'Keng-Yin Kwan', number: '6', birthdate: 1867, deathdate: 1919 },
	{ name: 'Yoke-Yue Cheong', number: '6S', birthdate: 1870, deathdate: 1944 },
	{ name: 'Sung-Sing Kwan', number: '6-1', birthdate: 1892, deathdate: 1960 },

	{ name: 'Keng-Leung', number: '7', birthdate: 1869, deathdate: 1945 },
	{ name: 'Yuet-Ngoh Lee', number: '7S1', birthdate: 1876, deathdate: 1905 },
	{ name: 'Kin-Mun Kwan', number: '7-1', birthdate: 1893, deathdate: 1910 },
	{ name: 'Kin-Tong Kwan', number: '7-2', birthdate: 1894, deathdate: 1965 },
	{ name: 'Khoon-Peng Lee', number: '7-2S', birthdate: 1902, deathdate: 1976 },
	{ name: 'Peter Mun-Chiew Kwan', number: '7-2-1', birthdate: 1920, deathdate: 2003 },
	{ name: 'Irene Siew-Chan Yap', number: '7-2-1S', birthdate: 1916, deathdate: 1997 },
	{ name: 'Eric Poon-Sinn Kwan', number: '7-2-1-1' },
	{ name: 'Joe Mun-Choe Kwan', number: '7-2-2', birthdate: 1921 },
	{ name: 'Koon-Ying Chow', number: '7-2-2S', birthdate: 1936 },
	{ name: 'Poon-Seng Kwan', number: '7-2-2-1' },
	{ name: 'Yoke-Lin Kwan', number: '7-2-2-2' },
	{ name: 'Gloria Mun-Cheok Kwan', number: '7-2-3', birthdate: 1923, deathdate: 1995 },
	{ name: 'Sung Ching George Ling', number: '7-2-3S', birthdate: 1925, deathdate: 2015 },
	{ name: 'Tsin-Yuen Jeanne Ling', number: '7-2-3-1', birthdate: 1952 },
	{ name: 'Leon Dail McLawhorn', number: '7-2-3-1S', birthdate: 1950 },
	{ name: 'Jennifer Kwan-Ling McLawhorn', number: '7-2-3-1-1', birthdate: 1987 },
	{ name: 'Sierra Kwan-Ling McLawhorn', number: '7-2-3-1-2', birthdate: 1995 },
	{ name: 'Meda Ling', number: '7-2-3-2', birthdate: 1954 },
	{ name: 'Guy L. Rando', number: '7-2-3-2S', birthdate: 1936 },
	{ name: 'Gaetano Ling', number: '7-2-3-2-1', birthdate: 1984 },
	{ name: 'Yoon Bahk', number: '7-2-3-2-1S' },
	{ name: 'Teo Rando Ling', number: '7-2-3-2-1-1', birthdate: 2016 },

	{ name: 'Yuet-Ying Kwan', number: '8', birthdate: 1870, deathdate: 1962 },
	{ name: 'Hoy Yung', number: '8S', birthdate: 1865, deathdate: 1933 },
	{ name: 'Kai-Mun Yung', number: '8-1', birthdate: 1893, deathdate: 1975 },
	{ name: 'Pui-Chan Poon', number: '8-1S', birthdate: 1898, deathdate: 1978 },
	{ name: 'Ying-Xi Rong', number: '8-1-1', birthdate: 1924, deathdate: 2003 },
	{ name: 'Li-Heng Zhong', number: '8-1-1S', birthdate: 1924 },
	{ name: 'Cheng-Zhao Rong', number: '8-1-1-1', birthdate: 1950 },
	{ name: 'Shi-Yu Zhong', number: '8-1-1-1S' },
	{ name: 'Victoria Yunyao Rong', number: '8-1-1-1-1' },
	{ name: 'Cheng-Zhang Rong', number: '8-1-1-2', birthdate: 1956 },
	{ name: 'Hai-Liang Zhang', number: '8-1-1-2S' },
	{ name: 'Tian-Lun Zhang', number: '8-1-1-2-1' },

	{ name: 'Keng-Choong Kwan', number: '9', birthdate: 1873, deathdate: 1923 },
	{ name: 'Sarah Chi-Sian Chu', number: '9S', birthdate: 1873, deathdate: 1940 },
	{ name: 'Margaret Fook-Heng Kwan', number: '9-1', birthdate: 1898, deathdate: 1991 },
	{ name: 'Tsai-Kuen Hu', number: '9-1S', birthdate: 1895, deathdate: 1984 },
	{ name: 'Olive Sun-Ru Hu', number: '9-1-1', birthdate: 1918, deathdate: 1999 },
	{ name: 'William Oh', number: '9-1-1S', birthdate: 1914, deathdate: 2000 },
	{ name: 'Gordon Min Hsien Oh', number: '9-1-1-1', birthdate: 1939},
	{ name: 'Ruby Chan', number: '9-1-1-1S' },
	{ name: 'Andrew Oh', number: '9-1-1-1-1' },
	{ name: 'Gerald Oh', number: '9-1-1-1-2' },

	{ name: 'Yuet-Har Kwan', number: '10', birthdate: 1874, deathdate: 1942 },

	{ name: 'Yuet-Wah Kwan', number: '11', birthdate: 1875 },
	{ name: 'Kwen-Choong Tham', number: '11S', birthdate: 1875, deathdate: 1902 },
	{ name: 'David Sui-Wai Tham', number: '11-1', birthdate: 1912, deathdate: 1943, note: 'reference 14-1S' },

	{ name: 'Keng-Sing (Sum Mun) Kwan', number: '12', birthdate: 1877, deathdate: 1955 },
	{ name: 'Shun-Wah Yeung', number: '12S', birthdate: 1884, deathdate: 1951 },
	{ name: 'Iu-Foon Kwan', number: '12-1', birthdate: 1910, deathdate: 2003, note: 'adopted: see 6-11' },
	{ name: 'Choon-Siew Chew', number: '12-1S', birthdate: 1905, deathdate: 1994 },
	{ name: 'Barbara Weng-San Chew', number: '12-1-1', birthdate: 1933 },
	{ name: 'Hsiu Sheng Hsu', number: '12-1-1S', birthdate: 1931 },
	{ name: 'Wei-Ming Hsu', number: '12-1-1-1', birthdate: 1964 },
	{ name: 'Peter Coutlakis', number: '12-1-1-1S', birthdate: 1963 },
	{ name: 'Nicholas J. Coutlakis', number: '12-1-1-1-1', birthdate: 2001 },
	{ name: 'Mira C. Coutlakis', number: '12-1-1-1-2', birthdate: 2003 },

	{ name: 'Chee-Woh (Keng Sun) Kwan', number: '13', birthdate: 1878, deathdate: 1948 },
	{ name: 'Julia Loke', number: '13S' },
	{ name: 'Wing-Hong Kwan', number: '13-1', birthdate: 1908, deathdate: 1973 },
	{ name: 'Marquita Oliver Scott', number: '13-1S1', birthdate: 1916, deathdate: 1993 },
	{ name: 'Ka-Keung Kwan', number: '13-1-1' },
	{ name: 'Moyra Elizabeth Cupit', number: '13-1-1S' },
	{ name: 'Oliver Hong Kwan ', number: '13-1-1-1' },
	{ name: 'Elliot Keung Kwan', number: '13-1-1-2' },
	{ name: 'Nicholas Wohl Kwan', number: '13-1-1-3' },
	{ name: 'Nancy Ka-Shen Kwan', number: '13-1-2' },
	{ name: 'Bernhard Pock', number: '13-1-2-1', birthdate: 1963, deathdate: 1996 },
	{ name: 'Yin-Chin Soong', number: '13-1S2', birthdate: 1922, deathdate: 2002 },
	{ name: 'Betty Ka-Ching Kwan', number: '13-1-3' },
	{ name: 'Derek Jeremy Leung', number: '13-1-3-1' },
	{ name: 'Johnny Ka-Chong Kwan', number: '13-1-4' },
	{ name: 'Boon Yee Kwan', number: '13-1-4-1' },
	{ name: 'Boon Tim Kwan', number: '13-1-4-2' },
	{ name: 'Annie Ka-Din Kwan', number: '13-1-5' },
	{ name: 'Charles Alexander Williams', number: '13-1-5S' },
	{ name: 'Samantha Leigh Williams', number: '13-1-5-1' },
	{ name: 'Charles Travis Williams', number: '13-1-5-2' },
	{ name: 'Reggie Ka-Kin Kwan', number: '13-1-6' },
	{ name: 'Teddy Ka-Leung Kwan', number: '13-1-7' },
	{ name: 'Margaret Liddle', number: '13-1-7S' },
	{ name: 'Rachel Elizabeth Boon Ling Kwan', number: '13-1-7-1' },
	{ name: 'Jessica Grace Boon Chin Kwan', number: '13-1-7-2' },
	{ name: 'Amy Louise Boon Sze Kwan', number: '13-1-7-3' },

	{ name: 'Cheong-Ting (Keng Hang) Kwan', number: '14', birthdate: 1880, deathdate: 1956 },
	{ name: 'Lut-Sang Chan', number: '14S1', birthdate: 1885, deathdate: 1968 },
	{ name: 'Amy Hock-Wen Kwan', number: '14-1', birthdate: 1906 },
	{ name: 'David Sui-Wai Tham', number: '14-1S', birthdate: 1902, deathdate: 1943, note: 'also see 11-1' },
	{ name: 'Bobby Yun-Le/Kun Tan', number: '14-1-1', birthdate: 1935 },
	{ name: 'Wen-Ying Lee', number: '14-1-1S', birthdate: 1942 },
	{ name: 'Ming-Hui Tan', number: '14-1-1-1', birthdate: 1964 },
	{ name: 'Xiao-Hui Tan', number: '14-1-1-2', birthdate: 1967 },
	{ name: 'Yong-Hui Tan', number: '14-1-1-3', birthdate: 1968 },
	{ name: 'So-Nui Kwan', number: '14-2', birthdate: 1908, deathdate: 1908 },
	{ name: 'Zhang Kwan', number: '14-3', birthdate: 1921, deathdate: 2009 },
	{ name: 'Meng-Zhen Lin', number: '14-3S', birthdate: 1921, deathdate: 2003 },
	{ name: 'Sheng-Wang Kwan', number: '14-3-1', birthdate: 1945, deathdate: 2010 },
	{ name: 'Hao Wang', number: '14-3-1S', birthdate: 1934, deathdate: 2008 },
	{ name: 'Sheng-Cong Kwan', number: '14-3-2', birthdate: 1947 },
	{ name: 'Wen-Lin Li', number: '14-3-2S', birthdate: 1947 },
	{ name: 'Lily Lee', number: '14-3-2-1', birthdate: 1978 },
	{ name: 'Xiong Su', number: '14-3-2-1S', birthdate: 1977 },
	{ name: 'Hang Su', number: '14-3-2-1-1' },
	{ name: 'Sheng-Tong Kwan', number: '14-3-3', birthdate: 1949 },
	{ name: 'Shu-Qin Ma', number: '14-3-3S', birthdate: 1954 },
	{ name: 'Xin Kwan', number: '14-3-3-1', birthdate: 1982 },
	{ name: 'Sheng-Da Kwan', number: '14-3-4', birthdate: 1952 },
	{ name: 'Zhi-Qiang Liang', number: '14-3-4S', birthdate: 1951 },
	{ name: 'Rong Liang', number: '14-3-4-1', birthdate: 1985 },
	{ name: 'Sheng-Ming Kwan', number: '14-3-5', birthdate: 1954 },
	{ name: 'Chong-Lan Chang', number: '14-3-5S', birthdate: 1956 },
	{ name: 'Shuo Kwan', number: '14-3-5-1', birthdate: 1985 },
	{ name: 'Pei-Lan Jia', number: '14S2', birthdate: 1908, deathdate: 1964 },
	{ name: 'Hock-Yuen Kwan', number: '14-4', birthdate: 1923 },
	{ name: 'Chuan-Yi Liu', number: '14-4S', birthdate: 1922 },
	{ name: 'Jing-Yi Liu', number: '14-4-1' },
	{ name: 'Jing-Cheng Liu', number: '14-4-2' },
	{ name: 'Xue-Fen Kwan', number: '14-5', birthdate: 1925, deathdate: 1947 },
	{ name: 'Lu Kwan', number: '14-6', birthdate: 1930 },
	{ name: 'Jia-Ming Li', number: '14-6S', birthdate: 1936 },
	{ name: 'Ro-Jia Kwan', number: '14-6-1', birthdate: 1959 },
	{ name: 'Jusheng Wang', number: '14-6-1S', birthdate: 1956 },
	{ name: 'Zi Wang', number: '14-6-1-1', birthdate: 1984 },
	{ name: 'Ro-Hong Kwan', number: '14-6-2', birthdate: 1961 },
	{ name: 'Xue-Ting Kwan', number: '14-7', birthdate: 1934, deathdate: 2003 },
	{ name: 'Peng Choon Hoh', number: '14-7S', birthdate: 1934, deathdate: 2005 },
	{ name: 'Peng Hoh', number: '14-7-1' },
	{ name: 'Yat Hung Hoh', number: '14-7-2' },
	{ name: 'Tony Kwan', number: '14-8', birthdate: 1938, deathdate: 1986 },
	{ name: 'Ellen Chen', number: '14-8S' },
	{ name: 'Jean Kwan', number: '14-8-1' },
	{ name: 'Dwight Ritchie', number: '14-8-1S' },
	{ name: 'Danielle Christine Ritchie', number: '14-8-1-1', birthdate: 1995 },
	{ name: 'Lauren Taylor Ritchie', number: '14-8-1-2', birthdate: 1998 },
	{ name: 'Dwight Ki Ritchie', number: '14-8-1-3', birthdate: 2001 },
	{ name: 'Ada Kwan', number: '14-8-2' },

	{ name: 'Keng-Fai Kwan', number: '15', birthdate: 1883, deathdate: 1943 }
])
